# Generated by Django 5.2.12 on 2026-03-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
