# Generated by Django 5.2.12 on 2026-03-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneta', '0003_portfolio_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='market_cap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price_change_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
