# Generated by Django 5.2.12 on 2026-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneta', '0004_asset_company_name_asset_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
