# Generated by Django 5.2.12 on 2026-03-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneta', '0005_alter_asset_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
